version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
